### PR TITLE
Initial draft of a proposal for MonkeySpace

### PR DESCRIPTION
**Pull request by haacked**
Title is a bit provocative, but that's part of the goal. To provoke some critical thinking about how we should approach .NET OSS.

Hey @half-ogre, @xpaulbettsx, @niik. Would love to get some feedback on this draft. :)

### CODE REVIEW

**Comment by anaisbetts** [comment]
[Rendered Version](https://github.com/Haacked/talk-abstracts/blob/monkeyspace-2013/open-source-apocalypse.md)

**Comment by anaisbetts** [comment]
I love the sentiment for sure, the exact wording might need to be tweaked a bit so that the jimmies of the MS people don't get too rustled perhaps.

**Comment by haacked** [comment]
@xpaulbettsx any suggestions on how to not rustle jimmies? My intent wasn't to take a swing at Microsoft whatsoever but to say let's stop playing the victim and build a community that doesn't require their involvement, but welcomes it. But I agree, I don't want to rustle jimmies. But I did want a provocative title to spur interest. :)

**Comment by haacked** [comment]
Hey @shanselman, got some time to review this abstract for MonkeySpace?

**Comment by shanselman** [comment]
I find Github for this kind of work very confusing.

**Comment by shanselman** [comment]
We need more specifics here. Bullets. The idea is good though, but I'm assume you will need to talk about 
- licenses
- lawyers
- bosses
- patents

**Comment by haacked** [comment]
@shanselman thanks! I was worried the abstract was getting too long. I'll add a few bullets with specifics.

**Pull request merged**
