### PR TITLE
New talk

### PR DESCRIPTION
**Pull request by anaisbetts**
Hey Phil, I think this is a pretty cool new talk you should think about!

### CODE REVIEW

**Comment by niik** [comment]
:+1:

**Comment by evolvedlight** [comment]
:apple:

**Comment by stack72** [comment]
:neckbeard:

**Comment by anaisbetts** [comment]
:sparkles: :tada: :metal: :trollface: :neckbeard: :finnadie:

**Comment by rafek** [comment]
:+1:

**Comment by haacked** [comment]
Only if you dance with me @xpaulbettsx

**Comment by hyperletter** [comment]
The only thing better then a git session with xpaulbettsx would be to do this pull request.

**Comment by anaisbetts** [comment]
We can probably close this out :)

**Comment by haacked** [comment]
So I take it you don't want to come dance with me on stage?

**Pull request closed without merging**
